# URL and TAG definitions for dependencies
#
# Copyright 2022-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Generated by components.py.
#

set(ABSEIL_GIT_URL "https://github.com/abseil/abseil-cpp.git")
set(ABSEIL_GIT_TAG "4447c7562e3bc702ade25105912dce503f0c4010") # 20240722.0

set(CARES_GIT_URL "https://github.com/c-ares/c-ares.git")
set(CARES_GIT_TAG "b82840329a4081a1f1b125e6e6b760d4e1237b52") # cares-1_34_4

set(CCTZ_GIT_URL "https://github.com/google/cctz.git")
set(CCTZ_GIT_TAG "02918d62329ef440935862719829d061a5f4beba") # v2.3-78-g02918d6

set(GFLAGS_GIT_URL "https://github.com/gflags/gflags.git")
set(GFLAGS_GIT_TAG "827c769e5fc98e0f2a34c47cef953cc6328abced") # v2.2.2-42-g827c769

set(GLOG_GIT_URL "https://github.com/google/glog.git")
set(GLOG_GIT_TAG "a8e0007e96ff96145022c488e367da10f835c75d") # v0.6.0-rc1

set(GRPC_GIT_URL "https://github.com/google/grpc.git")
set(GRPC_GIT_TAG "b4ef7c141d960be62e0008601261bb22cecb5d40") # v1.69.0
set(GRPC_VERSION "1.69.0")

set(GTEST_GIT_URL "https://github.com/google/googletest.git")
set(GTEST_GIT_TAG "e2239ee6043f73722e7aa812a459f54a28552929") # release-1.11.0

set(JSON_GIT_URL "https://github.com/nlohmann/json.git")
set(JSON_GIT_TAG "760304635dc74a5bf77903ad92446a6febb85acf") # v3.10.1-30-g76030463

set(PROTOBUF_GIT_URL "https://github.com/google/protobuf.git")
set(PROTOBUF_GIT_TAG "2d4414f384dc499af113b5991ce3eaa9df6dd931") # v29.0
set(PROTOBUF_VERSION "29.0")
set(PROTOBUF_ABSL_PROVIDER "package")

set(RE2_GIT_URL "https://github.com/google/re2.git")
set(RE2_GIT_TAG "4be240789d5b322df9f02b7e19c8651f3ccbf205") # 2022-12-01

set(ZLIB_GIT_URL "https://github.com/madler/zlib")
set(ZLIB_GIT_TAG "09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851") # v1.3
