name: Build stratum dependencies

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows the workflow to be run from the Actions tab
  workflow_dispatch:

concurrency:
  # If workflow for PR or push is already running, stop it and start a new one.
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  #---------------------------------------------------------------------
  # Environment variables
  #---------------------------------------------------------------------
  DEPS_INSTALL_DIR: /opt/p4dev/x86deps
  DEPS_SRC_ARTIFACT: deps-source
  DEPS_SRC_TARBALL: deps-source.tar.gz
  DEPS_BIN_ARTIFACT: deps-binary
  DEPS_BIN_TARBALL: deps-ubuntu-latest-x86_64.tar.gz

jobs:
  build_stratum_deps:
    runs-on: ubuntu-latest

    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - name: Check out stratum-deps
        uses: actions/checkout@v4
        with:
          path: stratum-deps

      - name: Build stratum-deps
        working-directory: stratum-deps
        run: |
          sudo mkdir -pv --mode=go+w $DEPS_INSTALL_DIR
          cmake --version
          cmake -B build -DCMAKE_INSTALL_PREFIX=$DEPS_INSTALL_DIR -DGIT_PROGRESS=OFF
          cmake --build build -j8

      - name: Prune folder
        working-directory: stratum-deps
        run: |
          ./scripts/prune.sh
          find . -name '.git*' -exec rm -fr {} +
          rm -fr build/

      - name: Create preconfig file
        working-directory: stratum-deps
        run: ./scripts/preconfig.sh

      - name: Create assets
        run: |
          tar -czf $DEPS_SRC_TARBALL stratum-deps
          tar -czf $DEPS_BIN_TARBALL $DEPS_INSTALL_DIR

      - name: Upload source artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          name: ${{ env.DEPS_SRC_ARTIFACT }}
          path: ${{ env.DEPS_SRC_TARBALL }}
          retention-days: 30

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4.3.5
        with:
          name: ${{ env.DEPS_BIN_ARTIFACT }}
          path: ${{ env.DEPS_BIN_TARBALL }}
          retention-days: 30

