name: Build Stratum dependencies

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows the workflow to be run from the Actions tab
  workflow_dispatch:

jobs:
   build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Build Stratum dependencies
        run: |
          cmake -B build -DCMAKE_INSTALL_PREFIX=deps
          cmake --build build -j8

      - name: Remove unnecessary directories
        run: |
          ./scripts/prune.sh
          ./scripts/rmgit.sh
          pwd
