name: Build dependencies

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows the workflow to be run from the Actions tab
  workflow_dispatch:

concurrency:
  # If workflow for PR or push is already running, stop it and start a new one.
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
   build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Build dependencies
        run: |
          cmake --version
          cmake -B build -DCMAKE_INSTALL_PREFIX=/tmp/deps -DGIT_PROGRESS=OFF
          cmake --build build -j8

      - name: Prune folder
        run: |
          ./scripts/prune.sh
          find . -name '.git*' -exec rm -fr {} +
          rm -fr build/

      - name: Create tarballs
        run: |
          tar -czf /tmp/deps-source.tar.gz -C .. stratum-deps/
          tar -czf /tmp/deps-linux-x86_64.tar.gz --transform='s#^tmp/##g' /tmp/deps

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: artifacts
          path: |
            /tmp/deps-linux-x86_64.tar.gz
            /tmp/deps-source.tar.gz
          retention-days: 30
